version: '3.8'

services:
  web:
    build: .
    command: sh -c "ipfs_daemon & gunicorn secured_health_record_system.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/secured_health_record_system

  # ipfs:
  #   build: .
  #   command: ipfs daemon
  #   volumes:
  #     - .:/secured_health_record_system