# Generated by Django 5.1 on 2024-09-24 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_healthrecord_record_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='record_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
