# Generated by Django 5.1 on 2024-09-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_healthrecord_record_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='record_name',
        ),
    ]
