# Generated by Django 5.1 on 2024-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_healthrecord_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='record_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
