# Generated by Django 5.1 on 2024-09-26 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_healthrecord_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='signature',
            field=models.TextField(default=datetime.datetime(2024, 9, 26, 17, 46, 58, 457550, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
