# Generated by Django 5.1 on 2024-09-27 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
